"use client";

import { useMemo, useState } from "react";
import type React from "react";
import { ageProfile, annualSeries, associationPoints, associationStats, commonIndicators, formatDecimal, formatInt, latestYear, nationalityShare, type OfficialDataset, type Role } from "@/lib/national/official-data";
import { CONCEPTS, VARIABLE_DICTIONARY } from "@/lib/national/sources";
import { DualLineChart, GroupedPercentBars, Histogram, HorizontalBars, ScatterChart, StackedNationality } from "./charts";

function MethodBlocks({ specification, reading, caution }:{ specification:React.ReactNode; reading:React.ReactNode; caution:React.ReactNode }) {
  return <div className="methodGrid"><section className="methodBlock"><b>Spécification statistique</b><div>{specification}</div></section><section className="methodBlock"><b>Comment lire</b><div>{reading}</div></section><section className="methodBlock methodWarning"><b>Point de vigilance</b><div>{caution}</div></section></div>;
}
function Panel({title,eyebrow,actions,children}:{title:string;eyebrow?:string;actions?:React.ReactNode;children:React.ReactNode}) { return <section className="panel"><header className="panelHeader"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div><div className="panelActions">{actions}</div></header>{children}</section>; }
function Select({label,value,onChange,children}:{label:string;value:string|number;onChange:(v:string)=>void;children:React.ReactNode}) { return <label className="selectField"><span>{label}</span><select value={value} onChange={(e)=>onChange(e.target.value)}>{children}</select></label>; }
function Source({children}:{children:React.ReactNode}) { return <div className="sourceFoot">{children}</div>; }
function defaultIndicator(d:OfficialDataset){ const c=commonIndicators(d); return c.find(x=>x.toLowerCase().includes("violences physiques")) ?? c[0] ?? ""; }

export function EmploymentPanel({dataset}:{dataset:OfficialDataset}) {
  const rows=dataset.insee.observations.map(r=>({group:r.group,employment:r.employmentRate,activity:r.activityRate,unemployment:r.unemploymentRate}));
  const a=dataset.insee.observations.find(r=>r.group==="Immigrés"), b=dataset.insee.observations.find(r=>r.group.startsWith("Sans ascendance"));
  const gap=a&&b?a.employmentRate-b.employmentRate:null;
  return <Panel title="Immigration et marché du travail" eyebrow="INSEE · enquête Emploi · 2025"><GroupedPercentBars rows={rows}/><MethodBlocks specification={<>France hors Mayotte, logement ordinaire, 15–64 ans pour ce croisement. Unité : %. Chômage au sens du BIT. Source : Insee, enquête Emploi 2025.</>} reading={<>Comparer un même indicateur entre groupes en points de pourcentage. Emploi immigrés / sans ascendance directe : {gap===null?"—":`${formatDecimal(gap,1)} points`}.</>} caution={<>Comparaisons descriptives non ajustées : âge, sexe, diplôme, ancienneté de résidence, secteur et origine sociale peuvent structurer les écarts. Aucune causalité. Les tableaux détaillés d’emploi/activité/chômage peuvent avoir des champs d’âge différents.</>}/><Source><a href={dataset.sources.inseeControl.url} target="_blank" rel="noreferrer">Tableau INSEE</a> · <a href={dataset.sources.inseeMelodiAnnuel.url} target="_blank" rel="noreferrer">Melodi DD_EEC_ANNUEL</a></Source></Panel>;
}

export function VictimRankingPanel({dataset}:{dataset:OfficialDataset}) {
  const [year,setYear]=useState(latestYear(dataset));
  const data=useMemo(()=>dataset.ssmsi.annualTotals.filter(r=>r.role==="victimes"&&r.year===year&&r.nationality==="Ensemble"&&!r.secret&&r.value!==null).sort((a,b)=>(b.value??0)-(a.value??0)).slice(0,10).map(r=>({label:r.indicator,value:r.value as number})),[dataset,year]);
  return <Panel title="Victimes enregistrées : principaux indicateurs" eyebrow="SSMSI · France entière" actions={<Select label="Année" value={year} onChange={v=>setYear(+v)}>{dataset.ssmsi.years.map(y=><option key={y}>{y}</option>)}</Select>}><HorizontalBars data={data} unit="victimes"/><MethodBlocks specification={<>France entière, victimes enregistrées par police et gendarmerie, {year}. Unité : effectifs.</>} reading={<>Chaque barre compare un volume enregistré ; le classement porte sur les ordres de grandeur.</>} caution={<>Les catégories peuvent se recouvrir : ne pas les additionner. Dépôt de plainte, qualification et pratiques d’enregistrement influencent les résultats. Volume enregistré ≠ gravité ≠ prévalence réelle.</>}/><Source><a href={dataset.sources.ssmsiDataset.url} target="_blank" rel="noreferrer">SSMSI / ministère de l’Intérieur</a></Source></Panel>;
}

export function TrendPanel({dataset}:{dataset:OfficialDataset}) {
  const indicators=commonIndicators(dataset), [indicator,setIndicator]=useState(()=>defaultIndicator(dataset));
  const victims=useMemo(()=>annualSeries(dataset,"victimes",indicator),[dataset,indicator]), suspects=useMemo(()=>annualSeries(dataset,"mis_en_cause",indicator),[dataset,indicator]);
  return <Panel title="Série temporelle victimes / mis en cause" eyebrow="SSMSI · 2016–2025" actions={<Select label="Indicateur" value={indicator} onChange={setIndicator}>{indicators.map(x=><option key={x}>{x}</option>)}</Select>}><DualLineChart victims={victims} suspects={suspects}/><MethodBlocks specification={<>Courbe 1 : victimes enregistrées. Courbe 2 : personnes mises en cause dans des infractions élucidées. Même année et indicateur, unités statistiques distinctes.</>} reading={<>Analyser l’évolution propre de chaque série puis les ruptures et tendances. L’écart entre courbes n’est jamais un taux d’élucidation.</>} caution={<>Une affaire peut comporter plusieurs victimes et plusieurs mis en cause. Signalement, enregistrement, élucidation ou qualification modifient les séries. Mis en cause ≠ condamné.</>}/></Panel>;
}

export function AgeProfilePanel({dataset}:{dataset:OfficialDataset}) {
  const [role,setRole]=useState<Role>("victimes"), [indicator,setIndicator]=useState(()=>defaultIndicator(dataset)), [year,setYear]=useState(latestYear(dataset));
  const data=useMemo(()=>ageProfile(dataset,role,indicator,year).filter(r=>!r.secret&&r.value!==null).map(r=>({label:r.age,value:r.value as number})),[dataset,role,indicator,year]);
  return <Panel title="Profil par âge" eyebrow="SSMSI · effectifs" actions={<><Select label="Rôle" value={role} onChange={v=>setRole(v as Role)}><option value="victimes">Victimes</option><option value="mis_en_cause">Mis en cause</option></Select><Select label="Année" value={year} onChange={v=>setYear(+v)}>{dataset.ssmsi.years.map(y=><option key={y}>{y}</option>)}</Select><Select label="Indicateur" value={indicator} onChange={setIndicator}>{commonIndicators(dataset).map(x=><option key={x}>{x}</option>)}</Select></>}><Histogram data={data}/><MethodBlocks specification={<>Année {year}; sexe et nationalité agrégés ; classes d’âge exactes publiées ; unité : nombre observé.</>} reading={<>Visualiser la concentration des enregistrements selon l’âge.</>} caution={<>Effectifs ≠ taux. Les populations et amplitudes de classes diffèrent ; comparer des risques exige des dénominateurs démographiques et une standardisation.</>}/></Panel>;
}

export function NationalityPanel({dataset}:{dataset:OfficialDataset}) {
  const [role,setRole]=useState<Role>("victimes"), [year,setYear]=useState(latestYear(dataset)); const indicators=dataset.ssmsi.indicators[role];
  const data=useMemo(()=>indicators.map(indicator=>({indicator,share:nationalityShare(dataset,role,indicator,year)})).filter(x=>x.share!==null).map(x=>({label:x.indicator,french:x.share!.french,foreign:x.share!.foreign,foreignShare:x.share!.foreignShare})).sort((a,b)=>b.foreignShare-a.foreignShare).slice(0,14),[dataset,role,year,indicators]);
  return <Panel title="Composition par nationalité" eyebrow="SSMSI · barres empilées 100 %" actions={<><Select label="Rôle" value={role} onChange={v=>setRole(v as Role)}><option value="victimes">Victimes</option><option value="mis_en_cause">Mis en cause</option></Select><Select label="Année" value={year} onChange={v=>setYear(+v)}>{dataset.ssmsi.years.map(y=><option key={y}>{y}</option>)}</Select></>}><div className="formulaLine"><code>part étrangère = étrangère / (française + étrangère) × 100</code></div><StackedNationality data={data}/><MethodBlocks specification={<>Année {year}, rôle {role}. Calcul uniquement si Française et Étrangère sont toutes deux diffusées ; toute cellule secrétisée invalide la part.</>} reading={<>Composition de la base administrative : part des personnes enregistrées de nationalité étrangère.</>} caution={<>Ce n’est pas un taux par population. Nationalité étrangère ≠ immigration ; une personne naturalisée est française. Aucune inférence individuelle ni causalité.</>}/></Panel>;
}

export function AssociationsPanel({dataset}:{dataset:OfficialDataset}) {
  const indicators=commonIndicators(dataset), [indicator,setIndicator]=useState(()=>defaultIndicator(dataset)); const points=useMemo(()=>associationPoints(dataset,indicator),[dataset,indicator]), stats=useMemo(()=>associationStats(points),[points]);
  return <Panel title="Associations statistiques compatibles" eyebrow="Unité d’analyse : année nationale" actions={<Select label="Indicateur" value={indicator} onChange={setIndicator}>{indicators.map(x=><option key={x}>{x}</option>)}</Select>}>
    {points.length<3?<div className="refusalBox"><b>Calcul refusé.</b> Moins de trois années compatibles après exclusion des cellules secrétisées.</div>:<><div className="statsStrip"><div><span>Années</span><strong>{stats.n}</strong></div><div><span>Pearson r</span><strong>{formatDecimal(stats.pearson,3)}</strong></div><div><span>Spearman ρ</span><strong>{formatDecimal(stats.spearman,3)}</strong></div><div><span>R²</span><strong>{formatDecimal(stats.r2,3)}</strong></div><div><span>p-value indicative</span><strong>{stats.pValue===null?"—":stats.pValue<.001?"< 0,001":formatDecimal(stats.pValue,3)}</strong></div></div><ScatterChart data={points.map(p=>({year:p.year,x:p.victimsShare,y:p.suspectsShare}))}/></>}
    <MethodBlocks specification={<>Part étrangère parmi victimes versus part étrangère parmi mis en cause, même indicateur et mêmes années ; n={points.length}. Pearson, Spearman et R² descriptifs.</>} reading={<>Chaque point est une année nationale ; le dernier millésime est mis en évidence.</>} caution={<>Autocorrélation possible, tendance commune et corrélation fallacieuse, pas de contrôle de composition, aucune causalité ni inférence individuelle. Nationalité SSMSI ≠ immigration.</>}/>
  </Panel>;
}

function download(name:string,content:string,mime:string){const u=URL.createObjectURL(new Blob([content],{type:mime}));const a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);} const esc=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;
export function DataExplorer({dataset}:{dataset:OfficialDataset}) {
  const [q,setQ]=useState(""),[role,setRole]=useState("all"),[year,setYear]=useState("all"),[indicator,setIndicator]=useState("all"),[nationality,setNationality]=useState("all"),[sex,setSex]=useState("all"),[age,setAge]=useState("all");
  const obs=dataset.ssmsi.observations; const options=useMemo(()=>({indicators:[...new Set(obs.map(r=>r.indicator))].sort(),nationalities:[...new Set(obs.map(r=>r.nationality))].sort(),sexes:[...new Set(obs.map(r=>r.sex))].sort(),ages:[...new Set(obs.map(r=>r.age))].sort()}),[obs]);
  const filtered=useMemo(()=>obs.filter(r=>(role==="all"||r.role===role)&&(year==="all"||r.year===+year)&&(indicator==="all"||r.indicator===indicator)&&(nationality==="all"||r.nationality===nationality)&&(sex==="all"||r.sex===sex)&&(age==="all"||r.age===age)&&(!q||`${r.indicator} ${r.role} ${r.nationality} ${r.sex} ${r.age}`.toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>b.year-a.year),[obs,q,role,year,indicator,nationality,sex,age]);
  const headers=["role","year","indicator","nationality","sex","age","majority","value","secret","disseminationStatus"];
  return <Panel title="Explorateur de données" eyebrow="Observations officielles normalisées"><div className="explorerToolbar"><label className="searchField"><span>Recherche</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="indicateur, âge…"/></label><Select label="Rôle" value={role} onChange={setRole}><option value="all">Tous</option><option value="victimes">Victimes</option><option value="mis_en_cause">Mis en cause</option></Select><Select label="Année" value={year} onChange={setYear}><option value="all">Toutes</option>{dataset.ssmsi.years.map(y=><option key={y}>{y}</option>)}</Select><Select label="Indicateur" value={indicator} onChange={setIndicator}><option value="all">Tous</option>{options.indicators.map(x=><option key={x}>{x}</option>)}</Select><Select label="Nationalité" value={nationality} onChange={setNationality}><option value="all">Toutes</option>{options.nationalities.map(x=><option key={x}>{x}</option>)}</Select><Select label="Sexe" value={sex} onChange={setSex}><option value="all">Tous</option>{options.sexes.map(x=><option key={x}>{x}</option>)}</Select><Select label="Âge" value={age} onChange={setAge}><option value="all">Tous</option>{options.ages.map(x=><option key={x}>{x}</option>)}</Select></div><div className="tableMetaRow"><b>{filtered.length.toLocaleString("fr-FR")} lignes</b><div><button onClick={()=>download("laboratoire-insee-filtre.json",JSON.stringify(filtered,null,2),"application/json")}>Export JSON</button><button onClick={()=>download("laboratoire-insee-filtre.csv",[headers.join(","),...filtered.map(r=>headers.map(k=>esc((r as unknown as Record<string,unknown>)[k])).join(","))].join("\n"),"text/csv")}>Export CSV</button><a className="buttonLink" href="/data/official-national-observations.json" download>Fichier compact</a></div></div><div className="tableScroll"><table><thead><tr><th>Rôle</th><th>Année</th><th>Indicateur</th><th>Nationalité</th><th>Sexe</th><th>Âge</th><th>Majorité</th><th>Nombre</th><th>Diffusion</th></tr></thead><tbody>{filtered.slice(0,300).map((r,i)=><tr key={`${r.role}-${r.year}-${r.indicator}-${i}`} className={r.secret?"secretRow":""}><td>{r.role==="mis_en_cause"?"Mis en cause":"Victimes"}</td><td>{r.year}</td><td>{r.indicator}</td><td>{r.nationality}</td><td>{r.sex}</td><td>{r.age}</td><td>{r.majority}</td><td className="numberCell">{r.secret?"secr.":formatInt(r.value)}</td><td>{r.disseminationStatus||"—"}</td></tr>)}</tbody></table></div><div className="dictionary"><h3>Dictionnaire des variables</h3>{VARIABLE_DICTIONARY.map(([k,v])=><div key={k}><code>{k}</code><span>{v}</span></div>)}</div></Panel>;
}

export function QualityPanel({dataset}:{dataset:OfficialDataset}) { const q=dataset.quality; return <div className="stackedPanels"><Panel title="Qualité & méthodologie" eyebrow="Audit de reconstruction"><div className="qualityGrid">{[["Observations INSEE",q.inseeObservationCount],["Observations SSMSI",q.observationCount],["Totaux annuels",q.annualTotalCount],["Profils âge",q.ageProfileCount],["Profils sexe",q.sexProfileCount],["Cellules secrétisées",q.secretCount],["Complétude",`${q.completenessPercent} %`],["Réconciliations en échec",q.reconciliationIssueCount]].map(([k,v])=><div key={String(k)}><span>{k}</span><strong>{String(v)}</strong></div>)}</div><div className="auditText"><h3>Règles d’agrégation</h3><p>{dataset.meta.rules.ssmsiAnnualTotal}</p><p>{dataset.meta.rules.secret}</p><p>{dataset.meta.rules.nationalityReconciliation}</p><h3>Sources et extraction</h3><p>Extraction UTC : <code>{dataset.meta.generatedAtUtc}</code></p>{Object.entries(dataset.sources).map(([k,s])=><p key={k}><code>{k}</code> — <a href={s.url} target="_blank" rel="noreferrer">{s.url}</a></p>)}</div></Panel><Panel title="Définitions obligatoires" eyebrow="Unités et concepts"> <div className="conceptGrid">{CONCEPTS.map(c=><div key={c.term}><b>{c.term}</b><p>{c.definition}</p></div>)}</div></Panel></div>; }

export function JusticePanel({dataset}:{dataset:OfficialDataset}) { return <Panel title="Condamnations" eyebrow="Compatibilité des sources"><div className="unavailableBox"><b>{dataset.justice.message}</b><p>{dataset.justice.reason}</p><a href={dataset.sources.justice.url} target="_blank" rel="noreferrer">Catalogue officiel du ministère de la Justice</a></div><MethodBlocks specification={<>Aucune série de condamnations n’est fusionnée avec les unités policières tant qu’un fichier ouvert, récent, structuré et documenté n’est pas méthodologiquement compatible.</>} reading={<>L’absence est affichée explicitement plutôt que remplacée par un chiffre ancien ou une estimation.</>} caution={<>Mis en cause ≠ poursuivi ≠ condamné. Les dates, champs et unités du casier judiciaire diffèrent des enregistrements SSMSI.</>}/></Panel>; }

export function ObservationOverview({dataset}:{dataset:OfficialDataset}) { return <div className="overviewGrid"><div className="overviewMain"><EmploymentPanel dataset={dataset}/></div><div className="overviewSide"><TrendPanel dataset={dataset}/></div><div className="overviewFull"><VictimRankingPanel dataset={dataset}/></div><div className="overviewFull"><NationalityPanel dataset={dataset}/></div><div className="overviewFull"><DataExplorer dataset={dataset}/></div><div className="overviewFull"><QualityPanel dataset={dataset}/></div></div>; }
